import { randomUUID } from "node:crypto";
import { resolve } from "node:path";
import { pathToFileURL } from "node:url";
import type { DeploymentSeed } from "../seed/types.ts";

/**
 * Prints one deployment's seed as SQL. Nothing here connects to a database.
 *
 * The seed is a module whose default export is a `DeploymentSeed`
 * (`seed/types.ts`): that operator's own projects, reply templates, signature
 * and default service. The platform has none of its own; `seed/example.ts` is
 * an example, and a real deployment keeps its seed alongside its own Wrangler
 * configuration, outside this repository:
 *
 *   pnpm --filter @inquiry-platform/api seed ../my-deployment/seed.ts > seed.sql
 *
 * A relative path is resolved against the directory the command was started
 * from, not this package.
 *
 * Two reasons for generating a file instead of running statements:
 *
 * - the same output can be reviewed, applied to `--local`, and then applied to
 *   `--remote`, and it is obvious beforehand exactly what will run;
 * - every statement is an insert guarded by `WHERE NOT EXISTS`, so re-running
 *   the seed creates nothing twice and — the part that matters — **never
 *   overwrites a template an operator has edited in the admin screen.** The
 *   seed is where a template starts; D1 is where it lives afterwards.
 *
 *   pnpm --filter @inquiry-platform/api exec wrangler d1 execute DB \
 *     --local --file seed.sql
 */
const argument = process.argv[2];
if (!argument) {
  process.stderr.write("Usage: seed <path to a module whose default export is a DeploymentSeed>\n");
  process.exit(1);
}
// pnpm runs scripts from the package directory and records where it was
// started in INIT_CWD.
const path = resolve(process.env.INIT_CWD ?? process.cwd(), argument);
const seed = ((await import(pathToFileURL(path).href)) as { default?: DeploymentSeed }).default;
if (!seed || typeof seed !== "object") {
  process.stderr.write(`${path} has no default export.\n`);
  process.exit(1);
}

const now = new Date().toISOString();
const lines: string[] = [
  `-- Generated by scripts/seed.ts from ${JSON.stringify(argument)}. Safe to run more than once.`,
  "-- Every statement is a guarded insert: nothing is updated, nothing is deleted.",
  "",
];

/** SQLite string literal. The only values passed through it are the constants
 * in a seed module, but doubling quotes is the difference between a seed file and a
 * way to run arbitrary SQL if that ever stops being true. */
const text = (value: string | undefined): string =>
  value === undefined ? "NULL" : `'${value.replace(/'/g, "''")}'`;

for (const service of seed.services ?? []) {
  lines.push(
    `INSERT INTO services (id, name, slug, is_active)`,
    `SELECT ${text(service.id)}, ${text(service.name)}, ${text(service.slug)}, 1`,
    `WHERE NOT EXISTS (SELECT 1 FROM services WHERE id = ${text(service.id)});`,
    "",
  );
}

for (const app of seed.apps ?? []) {
  const id = randomUUID();
  lines.push(
    `INSERT INTO apps (id, slug, name, platform, status, description, bundle_id, public_url, support_url, app_store_url, created_at, updated_at)`,
    `SELECT ${text(id)}, ${text(app.slug)}, ${text(app.name)}, ${text(app.platform)}, ${text(app.status)}, ${text(app.description)}, ${text(app.bundleId)}, ${text(app.publicUrl)}, ${text(app.supportUrl)}, ${text(app.appStoreUrl)}, ${text(now)}, ${text(now)}`,
    `WHERE NOT EXISTS (SELECT 1 FROM apps WHERE slug = ${text(app.slug)});`,
    "",
  );

  for (const [index, link] of (app.links ?? []).entries()) {
    lines.push(
      `INSERT INTO app_links (id, app_id, type, label, url, sort_order, created_at, updated_at)`,
      `SELECT ${text(randomUUID())}, a.id, ${text(link.type)}, ${text(link.label)}, ${text(link.url)}, ${index * 10}, ${text(now)}, ${text(now)}`,
      `  FROM apps a WHERE a.slug = ${text(app.slug)}`,
      `   AND NOT EXISTS (SELECT 1 FROM app_links l WHERE l.app_id = a.id AND l.url = ${text(link.url)});`,
      "",
    );
  }
}

for (const template of seed.replyTemplates ?? []) {
  const scope = template.appSlug
    ? `(SELECT id FROM apps WHERE slug = ${text(template.appSlug)})`
    : "NULL";
  lines.push(
    `INSERT INTO reply_templates (id, key, name, category, app_id, subject, body, include_signature, is_active, sort_order, created_at, updated_at)`,
    `SELECT ${text(randomUUID())}, ${text(template.key)}, ${text(template.name)}, ${text(template.category)}, ${scope}, ${text(template.subject)}, ${text(template.body)}, ${template.includeSignature ? 1 : 0}, 1, ${template.sortOrder}, ${text(now)}, ${text(now)}`,
    `WHERE NOT EXISTS (SELECT 1 FROM reply_templates WHERE key = ${text(template.key)});`,
    "",
  );
}

if (seed.signature !== undefined) {
  lines.push(
    `INSERT INTO app_mail_settings (app_id, signature_text, updated_at)`,
    `SELECT NULL, ${text(seed.signature)}, ${text(now)}`,
    `WHERE NOT EXISTS (SELECT 1 FROM app_mail_settings WHERE app_id IS NULL);`,
    "",
  );
}

if (seed.defaultServiceId !== undefined) {
  // Only once the service exists: a setting naming a missing service would
  // stop tickets being opened for contacts without a Project.
  lines.push(
    `INSERT INTO platform_settings (key, value)`,
    `SELECT 'default_service_id', ${text(seed.defaultServiceId)}`,
    ` WHERE EXISTS (SELECT 1 FROM services WHERE id = ${text(seed.defaultServiceId)})`,
    `   AND NOT EXISTS (SELECT 1 FROM platform_settings WHERE key = 'default_service_id');`,
    "",
  );
}

process.stdout.write(lines.join("\n"));
